
package Sistema.model.vista;

import Sistema.model.bean.Archivo;
import Sistema.model.bo.ArchivoBo;
import Sistema.model.bo.EmpleadoBo;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class frmArchivo extends javax.swing.JFrame {
     private Archivo oArchivo;
    private int codigo;
    private String Nombre;
    private int Documento;
    private char opt;
    
    public frmArchivo(java.awt.Frame parent, boolean modal) {
        initComponents();
        lblcodigo.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchivo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btngrabar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnseleccionar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guardar y Leer PDF");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblArchivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArchivoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArchivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 469, 90));

        btngrabar.setText("Guardar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmodificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngrabar)
                    .addComponent(btnmodificar)
                    .addComponent(btneliminar)
                    .addComponent(btncancelar)
                    .addComponent(btnBuscar)
                    .addComponent(btnnuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 469, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnseleccionar.setText("Seleccionar...");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(btnseleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 330, -1));
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 31, 331, -1));

        jLabel1.setText("Nombre del archivo:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, 20));

        jLabel2.setText("Seleccionar archivo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 20));

        lblcodigo.setText("Codigo");
        jPanel2.add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 55, 20));
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 126, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 469, 90));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Guardar PDF en la base de Datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 469, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
//     seleccionar_pdf();       

    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        Nombre = txtnombre.getText();
        
        oArchivo = new Archivo();
        switch (opt) {
            case 'N':
                oArchivo.setArchivo(Nombre);
                try {
                    if (ArchivoBo.grabarArchivo(oArchivo)) {
                        JOptionPane.showMessageDialog(this, "Se Registró Correctamente", "MENSAJE --> ARCHIVO", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Registrar", "MENSAJE --> ARCHIVO", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "MENSAJE --> ARCHIVO", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 'M':
                codigo = Integer.parseInt(txtcodigo.getText());
                oArchivo.setIdArchivo(codigo);
                oArchivo.setArchivo(Nombre);
                
                try {
                    if (ArchivoBo.modificarArchivo(oArchivo)) {
                        JOptionPane.showMessageDialog(this, "Se Modificó Correctamente", "ARCHIVO", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Modificar", "ARCHIVO", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "ARCHIVOO", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        camposDeshabilitado();
        lblcodigo.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsConfirmarDeshabilitar();
        btnsEdicionHabilitar();
        
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
       if (codigo != 0) {
            opt = 'M';
            camposHabilitado();
            txtcodigo.setText("");
            txtnombre.setText("");
            lblcodigo.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + codigo);
            txtnombre.requestFocus();
            txtnombre.setText(Nombre);
            }
            btnsConfirmarHabilitar();
            btnsEdicionDeshabilitar();
//            JOptionPane.showMessageDialog(this, "Seleccione el ARCHIVO", "ARCHIVO", JOptionPane.ERROR_MESSAGE);
                                                
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void tblArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArchivoMouseClicked
      
    }//GEN-LAST:event_tblArchivoMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
     
        
         }                                         
    
    private void cargarDatos() {
        try {
            TableColumn columna;
            DefaultTableModel ArchivoTableModel = ArchivoBo.obtenerListaArchivo();
            tblArchivo.setModel(ArchivoTableModel);
            setAnchoColumnas();
            columna = tblArchivo.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void cargarDatosBuscar() {
        try {
            TableColumn columna;
            DefaultTableModel ArchivoTableModel = ArchivoBo.obtenerListaArchivoBuscar(txtnombre.getText());
            tblArchivo.setModel(ArchivoTableModel);
            setAnchoColumnas();
            columna = tblArchivo.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }    
    public void setAnchoColumnas() {
        JViewport scroll = (JViewport) tblArchivo.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tblArchivo.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tblArchivo.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (4 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (6 * ancho) / 100;
                    break;
                case 2:
                    anchoColumna = (10 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
        }
    
    }//GEN-LAST:event_btncancelarActionPerformed
 private void btnsEdicionDeshabilitar() {
        btnnuevo.setEnabled(false);
        btnmodificar.setEnabled(false);    
    }
    
    private void btnsEdicionHabilitar() {
        btnnuevo.setEnabled(true);
        btnmodificar.setEnabled(true);    
    }
    
    private void btnsConfirmarHabilitar() {
        btngrabar.setEnabled(true);   
    }
    
    private void btnsConfirmarDeshabilitar() {
        btngrabar.setEnabled(false);   
    }
    
    private void limpiarCampos() {
        txtnombre.setText("");
       
    }
    
    
    
    private void camposHabilitado() {
        txtnombre.setEnabled(true);
        
    }
    
    private void camposDeshabilitado() {
        txtnombre.setEnabled(false);
        
    }                                        

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
               opt = 'B';
        txtnombre.setEnabled(true);
        txtcodigo.setVisible(false);
        lblcodigo.setVisible(false);
        txtnombre.requestFocus();
        cargarDatosBuscar();

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 frmArchivo dialog = new frmArchivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tblArchivo;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
