package Sistema.model.vista;

import Sistema.model.bo.CargoBo;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lenovo
 */
public class frmBuscarCargo extends javax.swing.JDialog {

    private int tb;

    public frmBuscarCargo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    frmBuscarCargo(frmGeneral aThis, boolean b) {
        super(aThis, b);
        initComponents();
        this.setLocationRelativeTo(null);
        cargo = (frmGeneral) aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCargo = new javax.swing.JTable();
        jpOpciones = new javax.swing.JPanel();
        lbldocumento = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        rbIdCargo = new javax.swing.JRadioButton();
        rbNroDocumento = new javax.swing.JRadioButton();
        rbDocumento = new javax.swing.JRadioButton();
        rbDestinatario = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Cargo - Opciones");
        setMaximumSize(new java.awt.Dimension(910, 410));
        setPreferredSize(new java.awt.Dimension(910, 410));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Buscar Cargo");
        jLabel16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel16jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(194, 11, 390, 22);

        jSeparator1.setMinimumSize(new java.awt.Dimension(900, 2));
        jSeparator1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 39, 790, 2);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/iconfinder_Exit_132316.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalirjSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(630, 100, 80, 30);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/buscar.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarjSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(520, 100, 100, 30);

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jScrollPane1jSeparator1KeyPressed(evt);
            }
        });

        tblCargo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCargo.setMinimumSize(new java.awt.Dimension(900, 400));
        tblCargo.setPreferredSize(new java.awt.Dimension(900, 400));
        tblCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCargoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCargoMousePressed(evt);
            }
        });
        tblCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCargoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCargo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 142, 880, 250);

        jpOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbldocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldocumento.setText("Ingrese dato a Buscar");
        lbldocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbldocumentojSeparator1KeyPressed(evt);
            }
        });

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatoKeyPressed(evt);
            }
        });

        buttonGroup1.add(rbIdCargo);
        rbIdCargo.setText("Cargo Id");
        rbIdCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIdCargoMouseClicked(evt);
            }
        });
        rbIdCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIdCargoMouseClicked(evt);
            }
        });
        rbIdCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIdCargoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNroDocumento);
        rbNroDocumento.setText("Documento Nro");
        rbNroDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNroDocumentoMouseClicked(evt);
            }
        });
        rbNroDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNroDocumentoMouseClicked(evt);
            }
        });
        rbNroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNroDocumentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDocumento);
        rbDocumento.setText("Documento");
        rbDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDocumentoMouseClicked(evt);
            }
        });
        rbDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDocumentoMouseClicked(evt);
            }
        });
        rbDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDocumentoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDestinatario);
        rbDestinatario.setText("Destinatario");
        rbDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDestinatarioMouseClicked(evt);
            }
        });
        rbDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDestinatarioMouseClicked(evt);
            }
        });
        rbDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDestinatarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpOpcionesLayout = new javax.swing.GroupLayout(jpOpciones);
        jpOpciones.setLayout(jpOpcionesLayout);
        jpOpcionesLayout.setHorizontalGroup(
            jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbIdCargo)
                .addGap(34, 34, 34)
                .addComponent(rbNroDocumento)
                .addGap(32, 32, 32)
                .addComponent(rbDocumento)
                .addGap(32, 32, 32)
                .addComponent(rbDestinatario)
                .addGap(33, 33, 33))
            .addGroup(jpOpcionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbldocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpOpcionesLayout.setVerticalGroup(
            jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIdCargo)
                    .addComponent(rbNroDocumento)
                    .addComponent(rbDocumento)
                    .addComponent(rbDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        getContentPane().add(jpOpciones);
        jpOpciones.setBounds(10, 52, 513, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbldocumentojSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbldocumentojSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbldocumentojSeparator1KeyPressed

    private void txtDatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtDatoKeyPressed

    private void jLabel16jSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel16jSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16jSeparator1KeyPressed

    private void jSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator1KeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirjSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirjSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirjSeparator1KeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtDato.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese dato a buscar");
            txtDato.requestFocus();
        } else {
            cargarCargo(tb);
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarjSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarjSeparator1KeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_btnBuscarjSeparator1KeyPressed

    private void tblCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargoMouseClicked

    }//GEN-LAST:event_tblCargoMouseClicked

    private void tblCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCargoMousePressed
        if (evt.getClickCount() == 2) {
            int index = tblCargo.getSelectedRow(); //txtIdDocumentoCargo
            cargo.gettxtCodigoCargo().setText(tblCargo.getValueAt(index, 0).toString());
            cargo.getTxtIdDocumento().setText(tblCargo.getValueAt(index, 1).toString());
            cargo.getlblIdDocumentoCargo().setText(tblCargo.getValueAt(index, 2).toString());
            cargo.gettxtDocumentoCargo().setText(tblCargo.getValueAt(index, 4).toString());
            cargo.gettxtFechaCargo().setDate(Date.valueOf(tblCargo.getValueAt(index, 5).toString()));
            cargo.gettxtHoraCargo().setText(tblCargo.getValueAt(index, 6).toString());
            cargo.gettxtAreaCargo().setText(tblCargo.getValueAt(index, 7).toString());
            cargo.gettxtAsuntoCargo().setText(tblCargo.getValueAt(index, 8).toString());
            cargo.gettxtInstitucionCargo().setText(tblCargo.getValueAt(index, 9).toString());
            cargo.gettxtRecepcionistaCargo().setText(tblCargo.getValueAt(index, 10).toString());
            this.dispose();
        }
    }//GEN-LAST:event_tblCargoMousePressed

    private void jScrollPane1jSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1jSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1jSeparator1KeyPressed

    private void rbIdCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIdCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIdCargoActionPerformed

    private void rbNroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNroDocumentoActionPerformed

    private void rbDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDocumentoActionPerformed

    private void rbDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDestinatarioActionPerformed

    private void rbIdCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbIdCargoMouseClicked
        if (rbIdCargo.isSelected() == true) {
            tb = 1;
        }
    }//GEN-LAST:event_rbIdCargoMouseClicked

    private void rbNroDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNroDocumentoMouseClicked
        if (rbNroDocumento.isSelected() == true) {
            tb = 2;
        }
    }//GEN-LAST:event_rbNroDocumentoMouseClicked

    private void rbDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDocumentoMouseClicked
        if (rbDocumento.isSelected() == true) {
            tb = 3;
        }
    }//GEN-LAST:event_rbDocumentoMouseClicked

    private void rbDestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDestinatarioMouseClicked
        if (rbDestinatario.isSelected() == true) {
            tb = 4;
        }
    }//GEN-LAST:event_rbDestinatarioMouseClicked

    private void tblCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCargoKeyPressed
    }//GEN-LAST:event_tblCargoKeyPressed
    private void cargarCargo(int tb) {
        switch (tb) {
            case 1:
                try {
                    TableColumn columna;
                    int idCarg = Integer.parseInt(txtDato.getText());
                    cargTableModel = CargoBo.buscarCargosIdCargo(idCarg);
                    tblCargo.setModel(cargTableModel);
                    setAnchoColumnas();
                    columna = tblCargo.getColumnModel().getColumn(0);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case 2:
                try {
                    TableColumn columna;
                    int idDoc = Integer.parseInt(txtDato.getText());
                    cargTableModel = CargoBo.buscarCargosIdDocumento(idDoc);
                    tblCargo.setModel(cargTableModel);
                    setAnchoColumnas();
                    columna = tblCargo.getColumnModel().getColumn(0);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case 3:
                try {
                    TableColumn columna;
                    String documento = txtDato.getText();
                    cargTableModel = CargoBo.buscarCargosDocumento(documento);
                    tblCargo.setModel(cargTableModel);
                    setAnchoColumnas();
                    columna = tblCargo.getColumnModel().getColumn(0);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case 4:
                try {
                    TableColumn columna;
                    String destinatario = txtDato.getText();
                    cargTableModel = CargoBo.buscarCargosDestinatario(destinatario);
                    tblCargo.setModel(cargTableModel);
                    setAnchoColumnas();
                    columna = tblCargo.getColumnModel().getColumn(0);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
        }
    }

    public void setAnchoColumnas() {
        TableColumn columna;
        TableColumnModel columnModel = tblCargo.getColumnModel();
        String titu[] = {"ID", "TD", "N°-DOC", "DOCUMENTO", "FECHA", "HORA", "AREA", "ASUNTO", "INSTITUCION", "RECEPC", "ST",};
        cargTableModel.setColumnIdentifiers(titu);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblCargo.getModel());
        tblCargo.setRowSorter(sorter);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        DefaultTableCellRenderer tcc = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tcc.setHorizontalAlignment(SwingConstants.CENTER);
        columnModel.getColumn(0).setCellRenderer(tcc);
        columnModel.getColumn(0).setPreferredWidth(8);
        columnModel.getColumn(1).setCellRenderer(tcc);
        columnModel.getColumn(1).setPreferredWidth(5);
        columnModel.getColumn(2).setPreferredWidth(20);
        columnModel.getColumn(3).setPreferredWidth(190);
        columnModel.getColumn(4).setCellRenderer(tcc);
        columnModel.getColumn(4).setPreferredWidth(30);
        columnModel.getColumn(5).setPreferredWidth(20);
        columnModel.getColumn(6).setPreferredWidth(80);
        columnModel.getColumn(7).setPreferredWidth(50); //ASUNTO
        columnModel.getColumn(8).setPreferredWidth(50); //area
        columnModel.getColumn(9).setPreferredWidth(50); //INST
        columnModel.getColumn(10).setPreferredWidth(50); //INST
        columnModel.getColumn(11).setPreferredWidth(5);
        columna = tblCargo.getColumnModel().getColumn(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCargo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCargo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCargo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarCargo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarCargo dialog = new frmBuscarCargo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpOpciones;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JRadioButton rbDestinatario;
    private javax.swing.JRadioButton rbDocumento;
    private javax.swing.JRadioButton rbIdCargo;
    private javax.swing.JRadioButton rbNroDocumento;
    private javax.swing.JTable tblCargo;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
    private frmGeneral cargo;
    private DefaultTableModel cargTableModel;
}
