package Sistema.model.vista;

import Sistema.model.bean.Correlativos;
import Sistema.model.bean.Documento;
import Sistema.model.bean.TipoDocumento;
import Sistema.model.bean.Usuario;
import Sistema.model.bo.CorrelativosBo;
import Sistema.model.bo.DocumentoArchivoBo;
import Sistema.model.bo.DocumentoBo;
import Sistema.model.bo.DocumentoDestinatarioBo;
import Sistema.model.bo.UsuarioBo;
import Sistema.model.dao.CargoDaoImp;
import Sistema.model.dao.CorrelativosDaoImp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lenovo
 */
public class frmBuscarDocumento extends javax.swing.JDialog {

    /**
     * Creates new form frmBuscarDocumento
     */
    public frmBuscarDocumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    frmBuscarDocumento(frmGeneral aThis, boolean b) {
        super(aThis, b);
        initComponents();
        this.setLocationRelativeTo(null);
        documento = (frmGeneral) aThis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldocumento = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDocumento = new javax.swing.JTable();
        txtDocumento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 515));
        getContentPane().setLayout(null);

        lbldocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbldocumento.setText("Documento");
        lbldocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(lbldocumento);
        lbldocumento.setBounds(20, 40, 80, 20);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/buscar.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(480, 40, 90, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Buscar Documento");
        jLabel16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(230, 0, 390, 30);

        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(580, 40, 70, 20);

        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });

        tblDocumento = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDocumento.setMinimumSize(new java.awt.Dimension(898, 790));
        tblDocumento.setPreferredSize(new java.awt.Dimension(898, 790));
        tblDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDocumentoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDocumentoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDocumento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 850, 370);

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyPressed(evt);
            }
        });
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(100, 40, 370, 20);

        jSeparator1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSeparator1KeyPressed(evt);
            }
        });
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 30, 950, 2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            TableColumn columna;
            docTableModel = DocumentoBo.obtenerListaDocumentoBuscar(txtDocumento.getText());
            tblDocumento.setModel(docTableModel);
            String titu[] = {"COD", "TD", "N°-DOC", "FECHA", "AÑO", "DOCUMENTO", "FOL", "ASUNTO", "INSTITUCION", "AREA", "ST",};
            docTableModel.setColumnIdentifiers(titu);
            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tblDocumento.getModel());
            tblDocumento.setRowSorter(sorter);
            TableColumnModel columnModel = tblDocumento.getColumnModel();
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            DefaultTableCellRenderer tcc = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.RIGHT);
            tcc.setHorizontalAlignment(SwingConstants.CENTER);
            columnModel.getColumn(0).setCellRenderer(tcc);
            columnModel.getColumn(0).setPreferredWidth(10);
            columnModel.getColumn(1).setCellRenderer(tcc);
            columnModel.getColumn(1).setPreferredWidth(4);
            columnModel.getColumn(2).setPreferredWidth(15);
            columnModel.getColumn(3).setPreferredWidth(40);
            columnModel.getColumn(4).setCellRenderer(tcc);
            columnModel.getColumn(4).setPreferredWidth(10);
            columnModel.getColumn(5).setPreferredWidth(180);
            columnModel.getColumn(6).setCellRenderer(tcc);
            columnModel.getColumn(6).setPreferredWidth(8);
            columnModel.getColumn(7).setPreferredWidth(45); //ASUNTO
            columnModel.getColumn(8).setPreferredWidth(45); //area
            columnModel.getColumn(9).setPreferredWidth(45); //INST
            columnModel.getColumn(10).setPreferredWidth(5);
            columna = tblDocumento.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocumentoMouseClicked
        if (evt.getClickCount() >= 2) {
            int index = tblDocumento.getSelectedRow();
            documento.getTxtIdDocumento().setText(tblDocumento.getValueAt(index, 0).toString());
            // idtipoDocumento = ((TipoDocumento) cboTipoDocumento.getSelectedItem()).getIdTipoDocumento();
            // documento.getCboTipoDocumento().setSelectedItem(String.valueOf(tblDocumento.getModel().getValueAt(index, 1)));
            //documento.getCboTipoDocumento().setSelectedItem(tblDocumento.getValueAt(index, 1));
            documento.getLblNumeroDocumento().setText(tblDocumento.getValueAt(index, 2).toString());
            documento.getTxtFechaDocumento().setText(tblDocumento.getValueAt(index, 3).toString());
            documento.getTxtAnio().setText(tblDocumento.getValueAt(index, 4).toString());
            documento.getTxtDocumento().setText(tblDocumento.getValueAt(index, 5).toString());
            // documento.setSpPinner.(tblDocumento.getValueAt(index, 6));//getSpFolios().setValue(tblDocumento.getValueAt(index, 6).toString());
            documento.getTxtAsunto().setText(tblDocumento.getValueAt(index, 7).toString());
            documento.getTxtAreaDocumento().setText(tblDocumento.getValueAt(index, 8).toString());
            documento.getTxtInstitucion().setText(tblDocumento.getValueAt(index, 9).toString());
            poblarDestinatario((Integer) tblDocumento.getValueAt(index, 1), tblDocumento.getValueAt(index, 2).toString());
            //documento.getcboEstadoDocumento().setSelectedItem(tblDocumento.getValueAt(index, 10).toString());
            poblarArchivo((Integer) tblDocumento.getValueAt(index, 1), tblDocumento.getValueAt(index, 2).toString());
            //documento.getcboEstadoDocumento().setSelectedItem(tblDocumento.getValueAt(index, 10).toString());
            this.dispose();
        }

    }//GEN-LAST:event_tblDocumentoMouseClicked
    private void poblarDestinatario(int idTipoDoc, String nroDoc) {
        try {
            docTableDestinatario = DocumentoDestinatarioBo.buscarDocumentoDestinatario(idTipoDoc, nroDoc);
            //    private DefaultTableModel docTableArchivo
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void poblarArchivo(int idTipoDoc, String nroDoc) {
        try {
            docTableArchivo = DocumentoArchivoBo.buscarDocumentoArchivo(idTipoDoc, nroDoc);
            //    private DefaultTableModel docTableArchivo
        } catch (Exception ex) {
            ex.printStackTrace();
        }
//            modeloListaArchivo.addElement(Archivo);
//    }
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtDocumentoKeyPressed

    private void tblDocumentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDocumentoMousePressed
        if (evt.getClickCount() == 2) {
            int index = tblDocumento.getSelectedRow();
            // String idDoc = (String) tblDocumento.getValueAt(index, 0);
            documento.getTxtIdDocumento().setText(tblDocumento.getValueAt(index, 0).toString());
            documento.getTxtDocumento().setText(tblDocumento.getValueAt(index, 5).toString());
            documento.getTxtAsunto().setText(tblDocumento.getValueAt(index, 7).toString());
            documento.getTxtInstitucion().setText(tblDocumento.getValueAt(index, 8).toString());
            documento.getTxtAreaDocumento().setText(tblDocumento.getValueAt(index, 9).toString());
            documento.getLblNumeroDocumento().setText(tblDocumento.getValueAt(index, 2).toString());
            documento.getTxtAnio().setText(tblDocumento.getValueAt(index, 4).toString());
            documento.getTxtFechaDocumento().setText(tblDocumento.getValueAt(index, 3).toString());
            System.out.println(tblDocumento.getValueAt(index, 6).toString());
            Integer integer = Integer.parseInt(tblDocumento.getValueAt(index, 6).toString());
            documento.getSpFolios().setValue(integer);
            documento.getBtnModificarDocumento().setEnabled(true);
            documento.getBtnEliminarDocumento().setEnabled(true);
            documento.getBtnNuevoDocumento().setEnabled(false);
            documento.getBtnGrabarDocumento().setEnabled(false);
            documento.habilitarBotonesFormularioDocumento();
            documento.getCboTipoDocumento().setEnabled(false);
            poblarDestinatario((Integer) tblDocumento.getValueAt(index, 1), tblDocumento.getValueAt(index, 2).toString());
            poblarArchivo((Integer) tblDocumento.getValueAt(index, 1), tblDocumento.getValueAt(index, 2).toString());
            this.dispose();
        }
    }//GEN-LAST:event_tblDocumentoMousePressed

    private void jSeparator1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSeparator1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBuscarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmBuscarDocumento dialog = new frmBuscarDocumento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JTable tblDocumento;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
    private frmGeneral documento;
    private DefaultTableModel docTableModel;
    private DefaultTableModel docTableDestinatario;
    private DefaultTableModel docTableArchivo;
}
