package Sistema.model.vista;

import Sistema.model.bean.Empleado;

import Sistema.model.bo.EmpleadoBo;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Lenovo
 */
public class frmEmpleado extends javax.swing.JFrame {

    private Empleado oEmpleado;
    private int codigo;
    private String RazonSocial;
    private String RUCDNI;
    private String Telefono;
    private String email;
    private int estado;
    private char opt;

    /**
     * Creates new form frmEmpleado
     */
    public frmEmpleado(java.awt.Frame parent, boolean modal) {

        initComponents();
        lblcod.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcod = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btngrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRUCDNI = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkestado = new javax.swing.JCheckBox();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcod.setText("Codigo");
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        jLabel3.setText("Razon Social");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 20));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 50, -1));

        jLabel5.setText("Telefono ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 50, 20));

        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 60, -1));

        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });
        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });
        getContentPane().add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 380, -1));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtemailKeyTyped(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 380, -1));

        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/Guardar1.JPG"))); // NOI18N
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 50, 40));

        jLabel6.setText("RUC/DNI");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 20));

        txtRUCDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRUCDNIKeyTyped(evt);
            }
        });
        getContentPane().add(txtRUCDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/modiicar.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 40, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mantenimiento de Empleados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 390, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tblEmpleado.setAutoCreateRowSorter(true);
        tblEmpleado = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "RAZON SOCIAL", "DNI", "TELEFONO", "EMAIL", "ESTADO"
            }
        ));
        tblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEmpleadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 630, 140));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnNuevo.jpg"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 40, -1));

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/eliminar1.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 40, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnBuscar.jpg"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/cancelar2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 40));

        chkestado.setText("Estado");
        getContentPane().add(chkestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 60, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        RazonSocial = txtRazonSocial.getText();
        RUCDNI = txtRUCDNI.getText();
        Telefono = txttelefono.getText();
        email = txtemail.getText();
        if (chkestado.isSelected()) {
            estado = 0;
        } else {
            estado = 1;
        }
        oEmpleado = new Empleado();
        switch (opt) {
            case 'N':
                oEmpleado.setRazonSocial(RazonSocial);
                oEmpleado.setRUCDNI(RUCDNI);
                oEmpleado.setTelefono(Telefono);
                oEmpleado.setCorreo(email);
                oEmpleado.setEstado(estado);
                try {
                    if (EmpleadoBo.grabarEmpleado(oEmpleado)) {
                        JOptionPane.showMessageDialog(this, "Se Registró Correctamente", "MENSAJE --> EMPLEADO", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Registrar", "MENSAJE --> EMPLEADO", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "MENSAJE --> EMPLEADO", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 'M':
                codigo = Integer.parseInt(txtcodigo.getText());
                oEmpleado.setIdEmpleado(codigo);
                oEmpleado.setRazonSocial(RazonSocial);
                oEmpleado.setRUCDNI(RUCDNI);
                oEmpleado.setTelefono(Telefono);
                oEmpleado.setCorreo(email);
                oEmpleado.setEstado(estado);

                try {
                    if (EmpleadoBo.modificarEmpleado(oEmpleado)) {
                        JOptionPane.showMessageDialog(this, "Se Modificó Correctamente", "EMPLEADO", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Modificar", "EMPLEADO", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "EMPLEADO", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        camposDeshabilitado();
        lblcod.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsConfirmarDeshabilitar();
        btnsEdicionHabilitar();


    }//GEN-LAST:event_btngrabarActionPerformed

    private void cargarDatos() {
        try {
            TableColumn columna;
            DefaultTableModel EmpleadoTableModel = EmpleadoBo.obtenerListaEmpleado();
            tblEmpleado.setModel(EmpleadoTableModel);
            setAnchoColumnas();
            columna = tblEmpleado.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean isCellEditable(int rowIndex, int vColIndex) {
        return false;
    }

    private void cargarDatosBuscar() {
        try {
            TableColumn columna;
            DefaultTableModel EmpleadoTableModel = EmpleadoBo.obtenerListaEmpleadoBuscar(txtRazonSocial.getText());
            tblEmpleado.setModel(EmpleadoTableModel);
            setAnchoColumnas();
            columna = tblEmpleado.getColumnModel().getColumn(0);
            int index = tblEmpleado.getSelectedRow();
            int indexc = tblEmpleado.getSelectedColumn();
            isCellEditable(index, indexc);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setAnchoColumnas() {
        JViewport scroll = (JViewport) tblEmpleado.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tblEmpleado.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tblEmpleado.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (4 * ancho) / 100;
                    isCellEditable(tblEmpleado.getSelectedRow(), 0);
                    break;
                case 1:
                    anchoColumna = (6 * ancho) / 100;
                    break;
                case 2:
                    anchoColumna = (10 * ancho) / 100;
                    break;
                case 3:
                    anchoColumna = (23 * ancho) / 100;
                    break;
                case 4:
                    anchoColumna = (19 * ancho) / 100;
                    break;

            }
            columnaTabla.setPreferredWidth(anchoColumna);
        }
    }


    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
//        char TipoDeTecla = evt.getKeyChar();
//        if (!Character.isDigit(TipoDeTecla)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        char TipoDeTecla = evt.getKeyChar();
        if (Character.isDigit(TipoDeTecla)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtRUCDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCDNIKeyTyped
        char TipoDeTecla = evt.getKeyChar();
        if (!Character.isDigit(TipoDeTecla)) {
            evt.consume();

        }
    }//GEN-LAST:event_txtRUCDNIKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
//        char TipoDeTecla = evt.getKeyChar();
//        if (!Character.isDigit(TipoDeTecla)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyTyped
//        char TipoDeTecla = evt.getKeyChar();
//        if (Character.isDigit(TipoDeTecla)) {
//            evt.consume();
//        }
    }//GEN-LAST:event_txtemailKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (codigo != 0) {
            opt = 'M';
            camposHabilitado();
            txtcodigo.setText("");
            txtRazonSocial.setText("");
            txtRUCDNI.setText("");
            txttelefono.setText("");
            txtemail.setText("");
            lblcod.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + codigo);
            txtRazonSocial.requestFocus();
            txtRazonSocial.setText(RazonSocial);
            txtRUCDNI.setText(RUCDNI);
            txttelefono.setText(Telefono);
            txtemail.setText(email);
            if (estado == 0) {
                chkestado.setSelected(true);
            } else {
                chkestado.setSelected(false);
            }
            btnsConfirmarHabilitar();
            btnsEdicionDeshabilitar();
//            JOptionPane.showMessageDialog(this, "Seleccione el Empleado", "EMPLEADO", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnModificarActionPerformed
    }
    private void tblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadoMouseClicked
        try {
            int index = tblEmpleado.getSelectedRow();
            codigo = Integer.parseInt(tblEmpleado.getValueAt(index, 0).toString());
            RazonSocial = tblEmpleado.getValueAt(index, 1).toString();
            RUCDNI = tblEmpleado.getValueAt(index, 2).toString();
            Telefono = tblEmpleado.getValueAt(index, 3).toString();
            email = tblEmpleado.getValueAt(index, 4).toString();
//            int indexc = tblEmpleado.getSelectedColumn();
//            isCellEditable(index, indexc);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblEmpleadoMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        opt = 'N';
        lblcod.setVisible(true);
        txtcodigo.setVisible(true);
        txtcodigo.setEditable(false);
        txtRazonSocial.setEditable(true);
        txtRazonSocial.setText("");
        txtRUCDNI.setEditable(true);
        txtRUCDNI.setText("");
        txttelefono.setEditable(true);
        txttelefono.setText("");
        txtemail.setEditable(true);
        txtemail.setText("");
        btnsConfirmarHabilitar();
        btnsEdicionDeshabilitar();
        camposHabilitado();
        limpiarCampos();
        activarEstado(opt);
    }

    private void btnsEdicionDeshabilitar() {
        btnnuevo.setEnabled(false);
        btnModificar.setEnabled(false);
    }

    private void btnsEdicionHabilitar() {
        btnnuevo.setEnabled(true);
        btnModificar.setEnabled(true);
    }

    private void btnsConfirmarHabilitar() {
        btngrabar.setEnabled(true);
    }

    private void btnsConfirmarDeshabilitar() {
        btngrabar.setEnabled(false);
    }

    private void limpiarCampos() {
        txtRazonSocial.setText("");
        txtRUCDNI.setText("");
        txttelefono.setText("");
        txtemail.setText("");
    }

    private void activarEstado(char opt) {
        String dato = "N";
        if (opt == dato.charAt(0)) {
            chkestado.setSelected(true);
        } else {
            chkestado.setSelected(false);
        }
    }

    private void camposHabilitado() {
        txtRazonSocial.setEnabled(true);
        txtRUCDNI.setEnabled(true);
        txttelefono.setEnabled(true);
        txtemail.setEnabled(true);
        chkestado.setEnabled(true);
    }

    private void camposDeshabilitado() {
        txtRazonSocial.setEnabled(false);
        txtRUCDNI.setEnabled(false);
        txttelefono.setEnabled(false);
        txtemail.setEnabled(false);
        chkestado.setEnabled(false);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (codigo != 0) {
            opt = 'E';
            lblcod.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + codigo);
            txtRazonSocial.setText(RazonSocial);
            txtRUCDNI.setText(RUCDNI);
            txttelefono.setText(Telefono);
            txtemail.setText(email);
            try {
                int index = tblEmpleado.getSelectedRow();
                codigo = Integer.parseInt(tblEmpleado.getValueAt(index, 0).toString());
                if (opt == 'E') {
                    oEmpleado = new Empleado();
                    oEmpleado.setIdEmpleado(codigo);
                    int rpta = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar", "Empleado", JOptionPane.YES_NO_OPTION);
                    if (rpta == 0) {
                        if (EmpleadoBo.eliminarEmpleado(oEmpleado)) {
                            JOptionPane.showMessageDialog(this, "Se Eliminó Correctamente", "EMPLEADO",
                                    JOptionPane.INFORMATION_MESSAGE);
                            cargarDatos();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo Eliminar", "EMPLEADO",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "EMPLEADO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el EMPLEADO", "EMPLEADO", JOptionPane.ERROR_MESSAGE);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (opt == 'M') {
            lblcod.setVisible(false);
            txtcodigo.setVisible(false);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
        limpiarCampos();
        camposDeshabilitado();
        activarEstado(opt);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        opt = 'B';
        txtRazonSocial.setEnabled(true);
        txtRUCDNI.setEnabled(false);
        txttelefono.setEnabled(false);
        txtemail.setEnabled(false);
        txtcodigo.setVisible(false);
        lblcod.setVisible(false);
        txtRazonSocial.requestFocus();
        if (estado == 0) {
            chkestado.setSelected(true);
        } else {
            chkestado.setSelected(false);
        }

        cargarDatosBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadoMousePressed
        if (evt.getClickCount() == 2) {
            int index = tblEmpleado.getSelectedRow();
            int indexc = tblEmpleado.getSelectedColumn();
            if (indexc == 0) {
                JOptionPane.showMessageDialog(null, index + " " + indexc);
                isCellEditable(index, indexc);
            }
        }

    }//GEN-LAST:event_tblEmpleadoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmEmpleado dialog = new frmEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JCheckBox chkestado;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcod;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtRUCDNI;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

}
