package Sistema.model.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author sistemas
 */
public class FrmMenuSistema extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuSoftSalud
     */
    public FrmMenuSistema() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aplicarFondo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        DesktopPane = new javax.swing.JDesktopPane();
        panelFondo = new JPanelFondo();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuEmpleado = new javax.swing.JMenuItem();
        mnuPrograma = new javax.swing.JMenuItem();
        mnuRemitente = new javax.swing.JMenuItem();
        mnuOcupacion = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuPermisos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuOperaciones = new javax.swing.JMenu();
        mnuTramiteDeDocumentos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuReporteTramiteDoc = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setOpaque(false);

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        DesktopPane.add(panelFondo);
        panelFondo.setBounds(0, 10, 630, 370);
        panelFondo.getAccessibleContext().setAccessibleName("");
        panelFondo.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBorder(null);

        mnuMantenimiento.setText("Mantenimiento");

        mnuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/medico.gif"))); // NOI18N
        mnuEmpleado.setText("Empleado");
        mnuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadoActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuEmpleado);

        mnuPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/estcivil.gif"))); // NOI18N
        mnuPrograma.setText("Programa");
        mnuPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramaActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuPrograma);

        mnuRemitente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/empleado.png"))); // NOI18N
        mnuRemitente.setText("Remitente");
        mnuRemitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemitenteActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuRemitente);

        mnuOcupacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/ocupacion.gif"))); // NOI18N
        mnuOcupacion.setText("Archivo");
        mnuOcupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOcupacionActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuOcupacion);
        mnuMantenimiento.add(jSeparator2);

        mnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/usuario.png"))); // NOI18N
        mnuUsuario.setText("Usuario");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuUsuario);

        mnuPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/tipo_material.png"))); // NOI18N
        mnuPermisos.setText("Permisos");
        mnuPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPermisosActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuPermisos);
        mnuMantenimiento.add(jSeparator1);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/salir.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuSalir);

        jMenuBar1.add(mnuMantenimiento);

        mnuOperaciones.setText("Operaciones");

        mnuTramiteDeDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/atencion.gif"))); // NOI18N
        mnuTramiteDeDocumentos.setText("Tramite de Documentos");
        mnuTramiteDeDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTramiteDeDocumentosActionPerformed(evt);
            }
        });
        mnuOperaciones.add(mnuTramiteDeDocumentos);

        jMenuBar1.add(mnuOperaciones);

        jMenu1.setText("Reportes");

        jMenuItem1.setText("Reporte de Cargos");
        jMenu1.add(jMenuItem1);

        mnuReporteTramiteDoc.setText("Reporte de Tramites Documentos");
        jMenu1.add(mnuReporteTramiteDoc);

        jMenuItem2.setText("Reporte de Remitentes");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        mnuAcercaDe.setText("Acerca de..");
        jMenu2.add(mnuAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTramiteDeDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTramiteDeDocumentosActionPerformed
        frmGeneral frmMenu = new frmGeneral(this, true);
        frmMenu.setLocationRelativeTo(null);
        frmMenu.setVisible(true);
    }//GEN-LAST:event_mnuTramiteDeDocumentosActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        frmUsuario frmUsuarios = new frmUsuario(this, true);
        frmUsuarios.setLocationRelativeTo(null);
        frmUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuOcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOcupacionActionPerformed
        frmArchivo frmArchivos = new frmArchivo(this, true);
        frmArchivos.setLocationRelativeTo(null);
        frmArchivos.setVisible(true);
    }//GEN-LAST:event_mnuOcupacionActionPerformed

    private void mnuRemitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemitenteActionPerformed
        frmRemitente frmRemitentes = new frmRemitente(this, true);
        frmRemitentes.setLocationRelativeTo(null);
        frmRemitentes.setVisible(true);
    }//GEN-LAST:event_mnuRemitenteActionPerformed

    private void mnuProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramaActionPerformed
      frmPrograma frmProgramas = new  frmPrograma(this, true);
        frmProgramas.setLocationRelativeTo(null);
        frmProgramas.setVisible(true);
    }//GEN-LAST:event_mnuProgramaActionPerformed

    private void mnuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadoActionPerformed
        frmEmpleado frmEmpleados = new frmEmpleado(this, true);
        frmEmpleados.setLocationRelativeTo(null);
        frmEmpleados.setVisible(true);
    }//GEN-LAST:event_mnuEmpleadoActionPerformed

    private void mnuPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPermisosActionPerformed
        frmPermisos frmPermiso = new  frmPermisos(this, true);
       frmPermiso.setLocationRelativeTo(null);
        frmPermiso.setVisible(true);
    }//GEN-LAST:event_mnuPermisosActionPerformed

    public void aplicarFondo() {
        Dimension tamanoVentana = Toolkit.getDefaultToolkit().getScreenSize();
        panelFondo.setSize(tamanoVentana);
//         ((JPanelFondo) panelFondo).setImagen("src/Sistema/model.img/f_ss.jpg");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenuItem mnuEmpleado;
    private javax.swing.JMenu mnuMantenimiento;
    private javax.swing.JMenuItem mnuOcupacion;
    private javax.swing.JMenu mnuOperaciones;
    private javax.swing.JMenuItem mnuPermisos;
    private javax.swing.JMenuItem mnuPrograma;
    private javax.swing.JMenuItem mnuRemitente;
    private javax.swing.JMenuItem mnuReporteTramiteDoc;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTramiteDeDocumentos;
    private javax.swing.JMenuItem mnuUsuario;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

}
