
package Sistema.model.vista;

import Sistema.model.bean.Programa;
import Sistema.model.bo.ProgramaBo;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;


public class frmPrograma extends javax.swing.JFrame {

        private int Codigo;
	private String Programa;
	private String Descripcion;
	private String estado;
	private String Fecha;
        private char opt;
        private Programa oPrograma;
    
    public frmPrograma(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        lblcodigo.setVisible(false);
        txtcodigo.setVisible(false);
        try {
            JFormattedTextField txtFecha = new JFormattedTextField(new FormatoFecha());
            txtFecha.setValue(new Date());
            txtFecha.setEnabled(false);
        } catch (Exception e) {
        }
        cargarDatos();
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtPrograma = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrograma = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboestado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PROGRAMA");

        lblcodigo.setText("Codigo");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Programa");

        jLabel4.setText("estado");

        tblPrograma = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblPrograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO ", "PROGRAMA", "DESCRIPCION", "ESTADO ", "FECHA"
            }
        ));
        tblPrograma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblProgramaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrograma);

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnNuevo.jpg"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnGrabar.jpg"))); // NOI18N
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/modiicar.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/cancelar2.png"))); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/eliminar1.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnBuscar.jpg"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha");

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(jLabel4)))
                        .addGap(51, 51, 51)
                        .addComponent(cboestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblcodigo)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcodigo)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnnuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar)
                            .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        opt = 'N';
        lblcodigo.setVisible(true);
        txtcodigo.setVisible(true);
        txtcodigo.setEditable(false);
        txtDescripcion.setEditable(true);
        txtDescripcion.setText("");
        txtPrograma.setEditable(true);
        txtPrograma.setText("");
        cboestado.getSelectedItem();
        cboestado.setEditable(true);
        txtFecha.setEditable(true);
        txtFecha.setText("");
       btnsConfirmarHabilitar();
        btnsEdicionDeshabilitar();
        camposHabilitado();
        limpiarCampos();

        }

        private void cargarDatos() {
            try {
                TableColumn columna;
                DefaultTableModel ProgramaTableModel = ProgramaBo.obtenerListaPrograma();
                tblPrograma.setModel(ProgramaTableModel);
                setAnchoColumnas();
                columna = tblPrograma.getColumnModel().getColumn(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        private void cargarDatosBuscar() {
            try {
                TableColumn columna;
                DefaultTableModel ProgramaTableModel = ProgramaBo.obtenerListaPrograma(txtPrograma.getText());
                tblPrograma.setModel(ProgramaTableModel);
                setAnchoColumnas();
                columna = tblPrograma.getColumnModel().getColumn(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        public void setAnchoColumnas() {
            JViewport scroll = (JViewport) tblPrograma.getParent();
            int ancho = scroll.getWidth();
            int anchoColumna = 0;
            TableColumnModel modeloColumna = tblPrograma.getColumnModel();
            TableColumn columnaTabla;
            for (int i = 0; i < tblPrograma.getColumnCount(); i++) {
                columnaTabla = modeloColumna.getColumn(i);
                switch (i) {
                    case 0:
                    anchoColumna = (4 * ancho) / 100;
                    break;
                    case 1:
                    anchoColumna = (6 * ancho) / 100;
                    break;
                    case 2 :
                    anchoColumna = (6 * ancho) / 100;
                    break;
                    case 3:
                    anchoColumna = (6 * ancho) / 100;
                     break;
                    case 4:
                    anchoColumna = (6 * ancho) / 100;

                }
                columnaTabla.setPreferredWidth(anchoColumna);
            }
        }

        private void btnsEdicionDeshabilitar() {
            btnnuevo.setEnabled(false);
            btnModificar.setEnabled(false);

        }

        private void btnsEdicionHabilitar() {
            btnnuevo.setEnabled(true);
            btnModificar.setEnabled(true);

        }

        private void btnsConfirmarHabilitar() {
            btngrabar.setEnabled(true);

        }

        private void btnsConfirmarDeshabilitar() {
            btngrabar.setEnabled(false);

        }

        private void limpiarCampos() {
            txtDescripcion.setText("");
            txtPrograma.setText("");
            cboestado.getSelectedItem();
            cboestado.setEditable(true);
            txtFecha.setText("");
        }

        private void camposHabilitado() {
            txtDescripcion.setEnabled(true);
            txtPrograma.setEnabled(true);
            cboestado.setEnabled(true);
            txtFecha.setEnabled(true);
        }

        private void camposDeshabilitado() {
            txtDescripcion.setEnabled(false);
            txtPrograma.setEnabled(false);
            cboestado.setEnabled(false);
            txtFecha.setEnabled(false);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        Programa = txtPrograma.getText();
        Descripcion = txtDescripcion.getText();
        estado= cboestado.getSelectedItem().toString();
        Fecha = txtFecha.getText();
        
        oPrograma = new Programa();
        switch (opt) {
            case 'N':
            oPrograma.setPrograma(Programa);
            oPrograma.setDescripcion(Descripcion);
            oPrograma.setEstado(estado);
             oPrograma.setFecha(Fecha);

            try {
                if (ProgramaBo.grabarPrograma(oPrograma)) {
                    JOptionPane.showMessageDialog(this, "Se Registró Correctamente", "MENSAJE --> PROGRAMA", JOptionPane.INFORMATION_MESSAGE);
                    cargarDatos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo Registrar", "MENSAJE --> PROGRAMA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "MENSAJE --> PROGRAMA", JOptionPane.ERROR_MESSAGE);
            }
            break;
            case 'M':
           Codigo = Integer.parseInt(txtcodigo.getText());
            oPrograma.setIdPrograma(Codigo);
            oPrograma.setPrograma(Programa);
            oPrograma.setDescripcion(Descripcion);
            oPrograma.setEstado(estado);
            oPrograma.setFecha(Fecha);

            try {
                if (ProgramaBo.modificarPrograma(oPrograma)) {
                    JOptionPane.showMessageDialog(this, "Se Modificó Correctamente", "PROGRAMA", JOptionPane.INFORMATION_MESSAGE);
                    cargarDatos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo Modificar", "PROGRAMA", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "PROGRAMA", JOptionPane.ERROR_MESSAGE);
            }
            break;
        }
        camposDeshabilitado();
        lblcodigo.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsConfirmarDeshabilitar();
        btnsEdicionHabilitar();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (Codigo != 0) {
            opt = 'M';
            camposHabilitado();
            txtcodigo.setText("");
            txtDescripcion.setText("");
            txtPrograma.setText("");
            cboestado.getSelectedItem();
            txtFecha.setText("");
            lblcodigo.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + Codigo);
            txtPrograma.requestFocus();
            txtDescripcion.setText(Descripcion);
            cboestado.getSelectedItem();
            txtFecha.setText(String.valueOf(Fecha));
            
            btnsConfirmarHabilitar();
            btnsEdicionDeshabilitar();
            //            JOptionPane.showMessageDialog(this, "Seleccione el Remitente", "REMITENTE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        if (opt == 'M') {
            lblcodigo.setVisible(false);
            txtcodigo.setVisible(false);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
        limpiarCampos();
        camposDeshabilitado();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (Codigo != 0) {
            opt = 'E';
            lblcodigo.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + Codigo);
            txtPrograma.setText(Programa);
            txtDescripcion.setText(Descripcion);
            cboestado.getSelectedItem();
            try {
                Codigo = Integer.parseInt(txtcodigo.getText());

                if (opt == 'E') {
                    oPrograma = new Programa();
                    oPrograma.setIdPrograma(Codigo);
                    int rpta = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar",
                        "PROGRAMA", JOptionPane.YES_NO_OPTION);
                    if (rpta == 0) {
                        if (ProgramaBo.eliminarPrograma(oPrograma)) {
                            JOptionPane.showMessageDialog(this, "Se Eliminó Correctamente", "PROGRAMA",
                                JOptionPane.INFORMATION_MESSAGE);
                            cargarDatos();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo Eliminar", "PROGRAMA",
                                JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "PROGRAMA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el Remitente", "PROGRAMA", JOptionPane.ERROR_MESSAGE);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        opt = 'B';
        txtPrograma.setEnabled(true);
        txtDescripcion.setEnabled(false);
        txtFecha.setEnabled(false);
        txtcodigo.setEnabled(false);
        txtPrograma.requestFocus();
        cargarDatosBuscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblProgramaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProgramaKeyTyped
       try {
            int index = tblPrograma.getSelectedRow();
            Codigo = Integer.parseInt(tblPrograma.getValueAt(index, 0).toString());
            Programa = tblPrograma.getValueAt(index, 1).toString();
           Descripcion = tblPrograma.getValueAt(index, 2).toString();
            estado = tblPrograma.getValueAt(index, 3).toString();
             Fecha= tblPrograma.getValueAt(index, 4).toString();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblProgramaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrograma dialog = new frmPrograma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTable tblPrograma;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrograma;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables
}
