package Sistema.model.vista;

import Sistema.model.bean.Remitente;
import Sistema.model.bo.RemitenteBo;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class frmRemitente extends javax.swing.JFrame {

    private int codigo;
    private String DNI;
    private String Remitente;
    private String Direccion;
    private String Telefono;
    private String Email;
    private char opt;
    private Remitente oRemitente;

    public frmRemitente(java.awt.Frame parent, boolean modal) {

        initComponents();
        lblcod.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRemitente = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtRemitente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Remitentes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 390, -1));

        lblcod.setText("Codigo");
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 54, -1));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 110, -1));

        jLabel1.setText("DNI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, -1));

        lblder.setText("Remitente");
        getContentPane().add(lblder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 20));

        jLabel2.setText("Direccion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 50, 20));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 350, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remitentes Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tblRemitente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblRemitente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DNI", "REMITENTE", "DIRECCION", "TELEFONO", "EMAIL"
            }
        ));
        tblRemitente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRemitenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRemitente);
        if (tblRemitente.getColumnModel().getColumnCount() > 0) {
            tblRemitente.getColumnModel().getColumn(0).setHeaderValue("CODIGO");
            tblRemitente.getColumnModel().getColumn(1).setHeaderValue("DNI");
            tblRemitente.getColumnModel().getColumn(2).setHeaderValue("REMITENTE");
            tblRemitente.getColumnModel().getColumn(3).setHeaderValue("DIRECCION");
            tblRemitente.getColumnModel().getColumn(4).setHeaderValue("TELEFONO");
            tblRemitente.getColumnModel().getColumn(5).setHeaderValue("EMAIL");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 610, 140));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnNuevo.jpg"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 40, -1));

        btngrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/btnGrabar.jpg"))); // NOI18N
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 40, 40));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/modiicar.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 40, -1));

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/cancelar2.png"))); // NOI18N
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 40, 40));

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/eliminar1.png"))); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 40, 40));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, 40));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/model.img/buscar6.jpg"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 30));
        getContentPane().add(txtRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 350, -1));

        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 210, 30, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRemitenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRemitenteMouseClicked
        try {
            int index = tblRemitente.getSelectedRow();
            codigo = Integer.parseInt(tblRemitente.getValueAt(index, 0).toString());
            DNI = tblRemitente.getValueAt(index, 1).toString();
            Remitente = tblRemitente.getValueAt(index, 2).toString();
            Direccion = tblRemitente.getValueAt(index, 3).toString();
            Telefono = tblRemitente.getValueAt(index, 4).toString();
            Email = tblRemitente.getValueAt(index, 5).toString();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblRemitenteMouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        opt = 'N';
        txtDNI.setEditable(true);
        txtDNI.setText("");
        txtRemitente.setEditable(true);
        txtRemitente.setText("");
        txtDireccion.setEditable(true);
        txtDireccion.setText("");
        txtTelefono.setEditable(true);
        txtTelefono.setText("");
        txtEmail.setEditable(true);
        txtEmail.setText("");

        btnsConfirmarHabilitar();
        btnsEdicionDeshabilitar();
        camposHabilitado();
        limpiarCampos();

    }

    private void cargarDatos() {
        try {
            TableColumn columna;
            DefaultTableModel RemitenteTableModel = RemitenteBo.obtenerListaRemitente();
            tblRemitente.setModel(RemitenteTableModel);
            setAnchoColumnas();
            columna = tblRemitente.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

        private void cargarDatosBuscar() {
        try {
            TableColumn columna;
            DefaultTableModel RemitenteTableModel = RemitenteBo.obtenerListaRemitente();
            tblRemitente.setModel(RemitenteTableModel);
            setAnchoColumnas();
            columna = tblRemitente.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void setAnchoColumnas() {
        JViewport scroll = (JViewport) tblRemitente.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tblRemitente.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tblRemitente.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (4 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (6 * ancho) / 100;
                    break;
                case 2:
                    anchoColumna = (10 * ancho) / 100;
                    break;
                case 3:
                    anchoColumna = (23 * ancho) / 100;
                    break;
                     case 4:
                    anchoColumna = (23 * ancho) / 100;
                    break;
                     case 5:
                    anchoColumna = (23 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
        }
    }

    private void cargarDatosBuscarDNI() {
        try {
            TableColumn columna;
            DefaultTableModel RemitenteTableModel = RemitenteBo.obtenerListaRemitenteDNI(txtDNI.getText());
            tblRemitente.setModel(RemitenteTableModel);
            setAnchoColumnas();
            columna = tblRemitente.getColumnModel().getColumn(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void btnsEdicionDeshabilitar() {
        btnnuevo.setEnabled(false);
        btnModificar.setEnabled(false);

    }

    private void btnsEdicionHabilitar() {
        btnnuevo.setEnabled(true);
        btnModificar.setEnabled(true);

    }

    private void btnsConfirmarHabilitar() {
        btngrabar.setEnabled(true);

    }

    private void btnsConfirmarDeshabilitar() {
        btngrabar.setEnabled(false);

    }

    private void limpiarCampos() {
        txtDNI.setText("");
        txtRemitente.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
    }

    private void camposHabilitado() {
        txtDNI.setEnabled(true);
        txtRemitente.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtEmail.setEnabled(true);
    }

    private void camposDeshabilitado() {
        txtDNI.setEnabled(false);
        txtRemitente.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtEmail.setEnabled(false);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        opt = 'B';
        txtDNI.setEnabled(true);
        txtRemitente.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtcodigo.setVisible(false);
        lblcod.setVisible(false);
        txtDNI.requestFocus();
        cargarDatosBuscarDNI();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        DNI = txtDNI.getText();
        Remitente = txtRemitente.getText();
        Direccion = txtDireccion.getText();
        Telefono = txtTelefono.getText();
        Email = txtEmail.getText();
        oRemitente = new Remitente();
        switch (opt) {
            case 'N':
                oRemitente.setDNI(DNI);
                oRemitente.setRemitente(Remitente);
                oRemitente.setDireccion(Direccion);
                oRemitente.setTelefono(Telefono);
                oRemitente.setEmail(Email);
               
                try {
                    if (RemitenteBo.grabarRemitente(oRemitente)) {
                        JOptionPane.showMessageDialog(this, "Se Registró Correctamente", "MENSAJE --> REMITENTE", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Registrar", "MENSAJE --> REMITENTE", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "MENSAJE --> REMITENTE", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 'M':
                codigo = Integer.parseInt(txtcodigo.getText());
                oRemitente.setIdRemitente(codigo);
                oRemitente.setDNI(DNI);
                oRemitente.setRemitente(Remitente);
                oRemitente.setDireccion(Direccion);
                oRemitente.setTelefono(Telefono);
                oRemitente.setEmail(Email);
               
                try {
                    if (RemitenteBo.modificarRemitente(oRemitente)) {
                        JOptionPane.showMessageDialog(this, "Se Modificó Correctamente", "REMITENTE", JOptionPane.INFORMATION_MESSAGE);
                        cargarDatos();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo Modificar", "REMITENTE", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "REMITENTE", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        camposDeshabilitado();
        lblcod.setVisible(false);
        txtcodigo.setVisible(false);
        cargarDatos();
        btnsConfirmarDeshabilitar();
        btnsEdicionHabilitar();


    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (codigo != 0) {
            opt = 'M';
            camposHabilitado();
            txtcodigo.setText("");
            txtDNI.setText("");
            txtRemitente.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtEmail.setText("");
            lblcod.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + codigo);
            txtRemitente.requestFocus();
            txtDNI.setText(DNI);
            txtRemitente.setText(Remitente);
            txtDireccion.setText(Direccion);
            txtTelefono.setText(Telefono);
            txtEmail.setText(Email);
            btnsConfirmarHabilitar();
            btnsEdicionDeshabilitar();
//            JOptionPane.showMessageDialog(this, "Seleccione el Remitente", "REMITENTE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        if (opt == 'M') {
            lblcod.setVisible(false);
            txtcodigo.setVisible(false);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();
        limpiarCampos();
        camposDeshabilitado();


    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (codigo != 0) {
            opt = 'E';
            lblcod.setVisible(true);
            txtcodigo.setVisible(true);
            txtcodigo.setText("" + codigo);
            txtDNI.setText(DNI);
            txtRemitente.setText(Remitente);
            txtDireccion.setText(Direccion);
            txtTelefono.setText(Telefono);
            txtEmail.setText(Email);
           try {
                codigo = Integer.parseInt(txtcodigo.getText());
                
                if (opt == 'E') {
                    oRemitente = new Remitente();
                    oRemitente.setIdRemitente(codigo);
                    int rpta = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar",
                            "REMITENTE", JOptionPane.YES_NO_OPTION);
                    if (rpta == 0) {
                        if (RemitenteBo.eliminarRemitente(oRemitente)) {
                            JOptionPane.showMessageDialog(this, "Se Eliminó Correctamente", "REMITENTE",
                                    JOptionPane.INFORMATION_MESSAGE);
                            cargarDatos();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo Eliminar", "REMITENTE",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "REMITENTE", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione el Remitente", "REMITENTE", JOptionPane.ERROR_MESSAGE);
        }
        btnsEdicionHabilitar();
        btnsConfirmarDeshabilitar();


    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRemitente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRemitente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRemitente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRemitente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRemitente dialog = new frmRemitente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcod;
    private javax.swing.JLabel lblder;
    private javax.swing.JTable tblRemitente;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtRemitente;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables

}
